-- INGESTA DE CARTAS: LOTE 5 (NATURALEZA - FINAL)
-- Cartas: El Trueno, La Cueva, El Horizonte, La Lluvia, El Camino, La Hoja, El Jardín, El Mar, La Sombra, El Amanecer, El Ocaso, La Brisa, El Relámpago, El Nido

INSERT INTO cards (
    id, deck_id, name, type, image,
    interpretation_past, interpretation_present, interpretation_future,
    question_past, question_present, question_future,
    challenge_past, challenge_present, challenge_future,
    ritual_past, ritual_present, ritual_future,
    invitation
) VALUES 
-- CARTA 17: EL TRUENO
(
    'nature-trueno', 'nature', 'El Trueno', 'nature', 
    'https://images.unsplash.com/photo-1605727282302-24c74460edcf?q=80&w=1000&auto=format&fit=crop',
    'Hubo un momento en tu vida en el que una verdad irrumpió de forma brusca. Algo que estaba oculto salió a la luz y cambió tu percepción de una situación o de una persona. Aunque fue impactante, ese despertar te liberó de una ilusión.',
    'Estás en una fase de revelación. Algo que venías evitando mirar ya no puede seguir oculto. Ignorarlo ahora solo intensificaría la tensión interna.',
    'Una comprensión repentina transformará tu rumbo. No será suave, pero será profundamente honesta y necesaria.',
    '¿Qué verdad pasada te sacudió pero terminó liberándote?',
    '¿Qué verdad estás evitando reconocer ahora?',
    '¿Qué revelación podría cambiar tu manera de vivir?',
    'Recuerda una verdad dura que aceptaste y reconoce en voz alta cómo te fortaleció.',
    'Di hoy una verdad que has estado callando (aunque sea solo para ti).',
    'Durante tres días, observa cuándo te engañas a ti mismo.',
    'Respira profundo tres veces al reconocer tu verdad pasada.',
    'Coloca una mano sobre tu garganta al decir tu verdad.',
    'Cada vez que detectes un autoengaño, repite: “Elijo ver”.',
    'No todas las verdades llegan con suavidad. Algunas irrumpen para despertarte de un sueño cómodo.'
),
-- CARTA 18: LA CUEVA
(
    'nature-cueva', 'nature', 'La Cueva', 'nature', 
    'https://images.unsplash.com/photo-1502759683299-cdcd6974244f?q=80&w=1000&auto=format&fit=crop',
    'Hubo una etapa en la que te retiraste del mundo, ya fuera física o emocionalmente. Necesitabas sanar, protegerte o simplemente desaparecer un poco para recomponerte. Ese aislamiento te dio una profundidad que hoy aún te sostiene.',
    'Estás en un momento de recogimiento interior. No es huida; es integración. Tu alma te está pidiendo silencio, descanso y menos exposición.',
    'Emergerás de este retiro con una claridad más suave y una fuerza más estable. Lo que hoy parece quietud es preparación.',
    '¿Qué retiro pasado te ayudó a sanar?',
    '¿Dónde necesitas más silencio ahora?',
    '¿Qué parte de ti está preparándose para emerger?',
    'Recuerda una etapa de soledad y agradécete por haberla atravesado.',
    'Dedica hoy un rato a estar sin estímulos ni compañía.',
    'Durante tres días, reduce tu exposición al ruido externo.',
    'Cierra los ojos un minuto y repite: “Me cuidé y sané”.',
    'Apaga una luz o pantalla durante tu momento de retiro.',
    'Cada noche, di: “Estoy emergiendo a mi ritmo”.',
    'No todo retiro es huida. Hay silencios que son medicina y soledades que son sagradas.'
),
-- CARTA 19: EL HORIZONTE
(
    'nature-horizonte', 'nature', 'El Horizonte', 'nature', 
    'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1000&auto=format&fit=crop',
    'Hubo un momento en tu vida en el que algo se cerró y te obligó a mirar más allá de lo conocido. Ese final te empujó a imaginar un futuro distinto, aunque al principio no supieras cómo llegar a él.',
    'Estás en una fase de expansión mental y vital. Tu visión se está ampliando. Empiezas a percibir posibilidades que antes no contemplabas.',
    'Se abrirá una nueva etapa llena de sentido y dirección. Si sigues esa visión interior, tu vida se alineará con un propósito más claro.',
    '¿Qué cierre pasado te obligó a imaginar otro futuro?',
    '¿Qué posibilidad nueva estás empezando a ver?',
    '¿Qué visión de futuro te inspira ahora?',
    'Recuerda un final importante y nombra en voz alta qué abrió.',
    'Haz hoy algo que expanda tu perspectiva (leer, hablar, caminar).',
    'Durante tres días, visualiza tu futuro ideal un minuto al día.',
    'Respira profundo al recordar ese cierre y di: “Todo final abre”.',
    'Al hacer tu acción expansiva, repite: “Amplío mi visión”.',
    'Mira al horizonte real o imaginario y di: “Avanzo hacia esto”.',
    'No vivas mirando solo lo que ya conoces. Hay un horizonte interior llamándote.'
),
-- CARTA 20: LA LLUVIA
(
    'nature-lluvia', 'nature', 'La Lluvia', 'nature', 
    'https://images.unsplash.com/photo-1534274988757-a28bf1f539cf?q=80&w=1000&auto=format&fit=crop',
    'Hubo un periodo en tu vida en el que todo parecía desbordarse emocionalmente. Lloraste, soltaste, te vaciaste por dentro. Aunque fue intenso, esa descarga limpió heridas que llevabas tiempo acumulando.',
    'Estás en un momento de liberación emocional. Algo dentro de ti pide salir: tristeza, alivio, gratitud o cansancio. Reprimirlo ahora solo retrasaría tu sanación.',
    'Después de esta limpieza llegará una etapa más fértil. Te sentirás más liviano, más abierto y más dispuesto a recibir.',
    '¿Qué desahogo emocional pasado te ayudó a sanar?',
    '¿Qué emoción necesita salir ahora mismo?',
    '¿Qué parte de ti se volverá más fértil tras soltar?',
    'Recuerda un momento de llanto o desahogo y agradécete por haberlo permitido.',
    'Permítete hoy expresar una emoción sin contenerla (hablar, llorar, moverte).',
    'Durante tres días, nota cómo cambia tu estado tras soltar pequeñas tensiones.',
    'Coloca una mano sobre el pecho y respira al agradecerte.',
    'Lávate la cara o las manos conscientemente después de expresarte.',
    'Cada vez que sientas alivio, di: “Me limpio por dentro”.',
    'No te avergüences de lo que necesitas soltar. Las emociones no expresadas se vuelven peso.'
),
-- CARTA 21: EL CAMINO
(
    'nature-camino', 'nature', 'El Camino', 'nature', 
    'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1000&auto=format&fit=crop',
    'Hubo una elección en tu vida que marcó un antes y un después. Tal vez no sabías adónde te llevaba, pero decidiste avanzar. Ese primer paso sigue sosteniendo tu historia actual.',
    'Estás en una encrucijada. No todas las opciones son correctas para ti, aunque todas parezcan razonables. La claridad ahora no vendrá de la lógica, sino de tu coherencia interior.',
    'Se abrirá una dirección más alineada con quien realmente eres. No será la más fácil, pero será la más honesta.',
    '¿Qué decisión pasada cambió tu rumbo vital?',
    '¿En qué cruce vital te encuentras ahora?',
    '¿Qué dirección se siente más auténtica para ti?',
    'Recuerda tu primer paso importante y nómbralo en voz alta.',
    'Hoy, elige una pequeña acción alineada con tu verdad.',
    'Durante tres días, actúa cada día desde esa dirección.',
    'Da un paso consciente al recordar tu decisión pasada.',
    'Antes de tu acción, di: “Camino en coherencia”.',
    'Al final de cada día, di: “Sigo mi camino”.',
    'No todos los caminos están hechos para ti. Algunos solo muestran lo que no eres.'
),
-- CARTA 22: LA HOJA
(
    'nature-hoja', 'nature', 'La Hoja', 'nature', 
    'https://images.unsplash.com/photo-1502082553048-f009c37129b9?q=80&w=1000&auto=format&fit=crop',
    'Hubo un momento en el que tuviste que soltar algo que amabas. Aunque dolió, ese desprendimiento te enseñó que nada te pertenece para siempre.',
    'Estás en una etapa de desprendimiento. Algo en tu vida está pidiendo irse: una relación, un hábito, una expectativa o una versión de ti.',
    'Después de soltar, llegará una ligereza nueva. Lo que hoy se va deja espacio para algo más alineado.',
    '¿Qué soltaste que terminó liberándote?',
    '¿Qué estás listo para dejar ir ahora?',
    '¿Qué ligereza deseas sentir?',
    'Recuerda algo que soltaste y agradécete por haberlo hecho.',
    'Hoy, deja ir una pequeña cosa innecesaria.',
    'Durante tres días, observa qué cambia al soltar.',
    'Exhala profundo al recordar lo que soltaste.',
    'Tira conscientemente ese objeto o hábito que dejaste ir.',
    'Cada vez que sientas ligereza, di: “Estoy más libre”.',
    'Soltar no es perder: es despejar el camino para lo que realmente importa.'
),
-- CARTA 23: EL JARDÍN
(
    'nature-jardin', 'nature', 'El Jardín', 'nature', 
    'https://images.unsplash.com/photo-1558905619-17254263246a?q=80&w=1000&auto=format&fit=crop',
    'Hubo una etapa en tu vida en la que cuidaste algo con dedicación: una relación, un proyecto, una vocación. No siempre viste resultados inmediatos, pero esa constancia silenciosa dejó huellas profundas.',
    'Estás en un momento de cultivo consciente. Lo que hoy atiendas con paciencia crecerá. No es tiempo de exigir frutos, sino de nutrir procesos.',
    'Recogerás lo que hoy siembres. Si cuidas lo esencial sin descuidarte a ti, crearás una vida más armónica y fértil.',
    '¿Qué cuidaste en el pasado aunque nadie lo notara?',
    '¿Qué necesita hoy más atención y paciencia?',
    '¿Qué fruto deseas cosechar dentro de un tiempo?',
    'Recuerda algo que cuidaste con amor y agradécetelo.',
    'Haz hoy un gesto consciente de cuidado hacia algo o alguien.',
    'Durante tres días, repite ese gesto de cuidado.',
    'Coloca una mano sobre el pecho al agradecerte.',
    'Al hacer tu gesto de cuidado, di: “Estoy cultivando vida”.',
    'Cada día, repite: “Honro lo que crece”.',
    'No subestimes el poder de lo pequeño y constante. La vida se construye en gestos silenciosos.'
),
-- CARTA 24: EL MAR
(
    'nature-mar', 'nature', 'El Mar', 'nature', 
    'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?q=80&w=1000&auto=format&fit=crop',
    'Hubo un momento en tu vida en el que te enfrentaste a lo inmenso: una pérdida, un cambio radical, una verdad emocional profunda. Esa experiencia te mostró que hay fuerzas dentro de ti vastas como el mar.',
    'Estás conectado con tu inconsciente y tu mundo emocional profundo. Hay mareas internas que suben y bajan. Negarlas ahora sería perder una parte esencial de ti.',
    'Aprenderás a navegar tus profundidades sin miedo. Lo que hoy te abruma se convertirá en sabiduría emocional.',
    '¿Qué experiencia te hizo sentir pequeño pero fuerte a la vez?',
    '¿Qué emoción profunda estás sintiendo ahora?',
    '¿Qué parte emocional de ti estás listo para integrar?',
    'Recuerda una emoción intensa pasada y agradécete por haberla sobrevivido.',
    'Dedica hoy cinco minutos a sentir sin distraerte.',
    'Durante tres días, nombra una emoción diaria sin juzgarla.',
    'Respira profundo tres veces al recordar esa emoción.',
    'Coloca una mano sobre el vientre durante tu momento de sentir.',
    'Cada vez que nombres una emoción, di: “Me permito sentir”.',
    'No tengas miedo de tus profundidades. Tu mundo emocional no es un enemigo.'
),
-- CARTA 25: LA SOMBRA
(
    'nature-sombra', 'nature', 'La Sombra', 'nature', 
    'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=1000&auto=format&fit=crop',
    'Hubo partes de ti que aprendiste a esconder para ser aceptado o para sobrevivir. Reprimiste emociones, deseos o rasgos que no encajaban. Esa estrategia te protegió, pero también te fragmentó.',
    'Estás en una fase de conforntación interior. Algo que has negado de ti está pidiendo ser reconocido. Ignorarlo ahora solo aumentará el conflicto interno.',
    'Al integrar tu sombra, emergerá una versión más completa y poderosa de ti. Lo que hoy temes aceptar será mañana tu fortaleza.',
    '¿Qué parte de ti aprendiste a ocultar?',
    '¿Qué rasgo o emoción estás evitando reconocer?',
    '¿Qué poder interior nacería al aceptarte completo?',
    'Recuerda algo que ocultaste de ti y agradécete por haberte protegido.',
    'Reconoce hoy un rasgo tuyo que no te gusta sin juzgarlo.',
    'Durante tres días, observa cuándo aparece tu sombra.',
    'Coloca una mano sobre el corazón al agradecerte.',
    'Mírate al espejo y di: “Me acepto completo”.',
    'Cada vez que detectes tu sombra, di: “Te veo”.',
    'No viniste a este mundo para ser solo luz. Tu sombra no es un defecto.'
),
-- CARTA 26: EL AMANECER
(
    'nature-amanecer', 'nature', 'El Amanecer', 'nature', 
    'https://images.unsplash.com/photo-1470252649358-96f3e18508e9?q=80&w=1000&auto=format&fit=crop',
    'Hubo un momento en tu vida en el que tocaste fondo o atravesaste una noche oscura. Aunque no lo sabías entonces, ese cierre marcó el inicio de una nueva etapa más consciente.',
    'Estás saliendo de una fase densa. Empiezas a sentir ligereza, claridad y una energía renovada. Algo dentro de ti ya no es el mismo.',
    'Se abre un nuevo ciclo vital lleno de oportunidades alineadas. Si honras este renacer, tu vida tomará una dirección más auténtica.',
    '¿Qué noche oscura terminó transformándote?',
    '¿En qué área de tu vida estás renaciendo?',
    '¿Qué nuevo comienzo deseas honrar?',
    'Recuerda un cierre difícil y reconoce en voz alta cómo te cambió.',
    'Haz hoy algo simbólicamente nuevo (un hábito, un gesto, una elección).',
    'Durante tres días, repite una acción alineada con tu nuevo comienzo.',
    'Respira profundo tres veces al honrar tu transformación.',
    'Al hacer tu gesto nuevo, di: “Renazco”.',
    'Cada día, di: “Honro este nuevo ciclo”.',
    'No minimices tus renacimientos. Cada vez que sobrevives a una noche oscura, algo despierta.'
),
-- CARTA 27: EL OCASO
(
    'nature-ocaso', 'nature', 'El Ocaso', 'nature', 
    'https://images.unsplash.com/photo-1470252649358-96f3e18508e9?q=80&w=1000&auto=format&fit=crop',
    'Hubo una despedida o cierre que no querías aceptar. Aunque dolió, ese final marcó un punto de inflexión necesario en tu historia.',
    'Estás en una fase de conclusión. Algo importante está terminando. Resistirte ahora solo prolongará el duelo.',
    'Tras este cierre, llegará una paz más profunda. Lo que hoy termina dejará espacio para algo más honesto.',
    '¿Qué cierre pasado te costó aceptar?',
    '¿Qué está terminando ahora en tu vida?',
    '¿Qué paz deseas sentir tras este final?',
    'Recuerda una despedida pasada y agradécete por haberla atravesado.',
    'Despídete hoy conscientemente de algo que termina.',
    'Durante tres días, honra ese cierre sin intentar llenarlo.',
    'Exhala profundo al recordar esa despedida.',
    'Di en voz alta: “Dejo ir”.',
    'Cada día, repite: “Honro este final”.',
    'No todos los finales son fracasos. Algunos son actos de amor propio.'
),
-- CARTA 28: LA BRISA
(
    'nature-brisa', 'nature', 'La Brisa', 'nature', 
    'https://images.unsplash.com/photo-1505672678657-cc7037095e60?q=80&w=1000&auto=format&fit=crop',
    'Hubo señales sutiles que no supiste escuchar. Mensajes suaves que ignoraste por estar enfocado en lo urgente.',
    'Estás recibiendo guía silenciosa. No todo llega como un trueno; algunas verdades llegan como un susurro.',
    'Si aprendes a escuchar lo sutil, tu vida se volverá más sincronizada y fluida.',
    '¿Qué señal suave ignoraste en su momento?',
    '¿Qué susurro interior estás escuchando ahora?',
    '¿Qué pasaría si confiaras más en lo sutil?',
    'Recuerda una intuición pasada y agradécete por haberla tenido.',
    'Hoy, presta atención consciente a una señal pequeña.',
    'Durante tres días, escucha una intuición diaria.',
    'Respira suave tres veces al recordar tu intuición.',
    'Al notar tu señal, di: “Escucho”.',
    'Cada vez que sigas tu intuición, di: “Confío”.',
    'No subestimes la guía silenciosa de la vida. No todo lo verdadero grita.'
),
-- CARTA 29: EL RELÁMPAGO
(
    'nature-relampago', 'nature', 'El Relámpago', 'nature', 
    'https://images.unsplash.com/photo-1605727282302-24c74460edcf?q=80&w=1000&auto=format&fit=crop',
    'Hubo un instante de revelación que cambió tu percepción para siempre. Algo se iluminó de golpe.',
    'Estás a punto de ver algo con claridad súbita. No la rechaces por incomodidad.',
    'Un giro rápido reordenará tu vida.',
    '¿Qué revelación pasada te transformó?',
    '¿Qué verdad podría aparecer de golpe?',
    '¿Qué cambio rápido estás listo para aceptar?',
    'Recuerda una revelación pasada y reconoce su impacto.',
    'Mantente abierto hoy a una nueva verdad.',
    'Durante tres días, acepta un cambio inesperado.',
    'Respira profundo al recordar tu revelación.',
    'Di: “Estoy listo para ver”.',
    'Cada vez que algo cambie, di: “Acepto”.',
    'No temas a los cambios súbitos. La vida te sacude para devolverte a tu eje.'
),
-- CARTA 30: EL NIDO
(
    'nature-nido', 'nature', 'El Nido', 'nature', 
    'https://images.unsplash.com/photo-1544256718-3bcf237f3167?q=80&w=1000&auto=format&fit=crop',
    'Hubo un tiempo en el que buscaste protección, pertenencia o refugio. Tal vez no siempre lo encontraste afuera, pero empezaste a construirlo dentro de ti.',
    'Estás en una fase de cuidado y contención. Tu alma pide seguridad, ternura y raíces emocionales.',
    'Crearás un espacio de pertenencia auténtica, contigo mismo y con otros.',
    '¿Dónde buscaste refugio cuando lo necesitabas?',
    '¿Qué te hace sentir seguro ahora?',
    '¿Qué hogar interior deseas construir?',
    'Recuerda un momento en el que te sentiste protegido y agradécelo.',
    'Haz hoy algo que te haga sentir contenido.',
    'Durante tres días, repite un gesto de autocuidado.',
    'Coloca una mano sobre el pecho al agradecer.',
    'Abraza una almohada o a ti mismo y di: “Estoy a salvo”.',
    'Cada día, di: “Construyo mi hogar interior”.',
    'No estás aquí solo para resistir: estás aquí para habitarte.'
)
ON CONFLICT (id) DO UPDATE SET
interpretation_past = EXCLUDED.interpretation_past,
interpretation_present = EXCLUDED.interpretation_present,
interpretation_future = EXCLUDED.interpretation_future,
question_past = EXCLUDED.question_past,
question_present = EXCLUDED.question_present,
question_future = EXCLUDED.question_future,
challenge_past = EXCLUDED.challenge_past,
challenge_present = EXCLUDED.challenge_present,
challenge_future = EXCLUDED.challenge_future,
ritual_past = EXCLUDED.ritual_past,
ritual_present = EXCLUDED.ritual_present,
ritual_future = EXCLUDED.ritual_future,
invitation = EXCLUDED.invitation;
