-- Ingest script for Tarot Maestro: Minor Arcana (56 cards)
-- Restoring temporal fields to satisfy DB constraints

INSERT INTO cards (
    id, deck_id, name, type, card_type, number, suit, rank, image, 
    interpretation_past, interpretation_present, interpretation_future,
    question_past, question_present, question_future,
    challenge_past, challenge_present, challenge_future,
    ritual_past, ritual_present, ritual_future,
    invitation
)
VALUES 
-- BASTOS
('tarot_as_bastos', 'tarot_master', 'As de Bastos', 'fuego', 'minor', 1, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'El inicio de una gran pasión.', 'Semilla de un nuevo proyecto. Potencial absoluto.', 'Una idea florecerá pronto.', 
'¿Qué iniciaste?', '¿Qué nace hoy?', '¿Qué gestarás?', 
'Supera la duda.', 'Actúa con fe.', 'Mantén el fuego.', 
'Mira una brasa.', 'Enciende una vela roja.', 'Siente el calor del sol.', '¿Qué proyecto inicias hoy?'),

('tarot_2_bastos', 'tarot_master', 'Dos de Bastos', 'fuego', 'minor', 2, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'Cuando elegiste tu rumbo.', 'Elección de rumbo profesional. Dualidad.', 'Pronto decidirás tu destino.', 
'¿Qué camino tomaste?', '¿Qué eliges hoy?', '¿Qué elegirás?', 
'No dudes más.', 'Decide con valor.', 'Confía en tu plan.', 
'Dibuja dos senderos.', 'Mira un mapa.', 'Camina en línea recta.', '¿Cuál es tu próximo objetivo?'),

('tarot_3_bastos', 'tarot_master', 'Tres de Bastos', 'fuego', 'minor', 3, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'El horizonte que vislumbraste.', 'Expansión de tus proyectos. Primeros frutos.', 'Tus naves llegarán a puerto.', 
'¿Qué naves enviaste?', '¿Qué fruto ves hoy?', '¿Qué tierras conquistarás?', 
'No te detengas.', 'Amplía tu visión.', 'Confía en el éxito.', 
'Observa el mar.', 'Mira el horizonte.', 'Sube a un lugar alto.', '¿Qué tan lejos llegarás?'),

('tarot_4_bastos', 'tarot_master', 'Cuatro de Bastos', 'fuego', 'minor', 4, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La base que construiste.', 'Estabilidad laboral y celebración de logros.', 'Una base sólida te espera.', 
'¿Qué cimiento pusiste?', '¿Qué celebras hoy?', '¿Dónde te asentarás?', 
'Disfruta la paz.', 'Consolida tu base.', 'Mantén el orden.', 
'Baila en casa.', 'Decora tu espacio.', 'Invita a alguien.', '¿Qué éxito celebras hoy?'),

('tarot_5_bastos', 'tarot_master', 'Cinco de Bastos', 'fuego', 'minor', 5, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La lucha que enfrentaste.', 'Crisis de competencia o conflicto.', 'Aprenderás de la lucha.', 
'¿Con quién peleaste?', '¿Quién te desafía hoy?', '¿Cómo vencerás?', 
'No huyas.', 'Acepta el reto.', 'Domina el caos.', 
'Grita al viento.', 'Mueve un mueble.', 'Haz ejercicio.', '¿Cómo gestionas la tensión?'),

('tarot_6_bastos', 'tarot_master', 'Seis de Bastos', 'fuego', 'minor', 6, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'El honor que recibiste.', 'Armonía y reconocimiento tras el esfuerzo.', 'Tu victoria será pública.', 
'¿Quién te aplaudió?', '¿Qué mérito tienes hoy?', '¿Cómo brillarás?', 
'Sé humilde.', 'Acepta la gloria.', 'Comparte el éxito.', 
'Ponte una corona.', 'Viste de gala.', 'Camina con orgullo.', '¿Qué victoria compartes?'),

('tarot_7_bastos', 'tarot_master', 'Siete de Bastos', 'fuego', 'minor', 7, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La posición que defendiste.', 'Perseverancia frente a la oposición.', 'Mantendrás tu terreno.', 
'¿Qué defendiste?', '¿Qué cuidas hoy?', '¿Hasta dónde llegarás?', 
'No te rindas.', 'Resiste con fuerza.', 'Confía en tu vara.', 
'Grita "puedo".', 'Párate firme.', 'Sostén un palo.', '¿Cuál es tu mayor reto?'),

('tarot_8_bastos', 'tarot_master', 'Ocho de Bastos', 'fuego', 'minor', 8, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La rapidez del cambio.', 'Dominio del ritmo. Noticias rápidas.', 'Todo sucederá velozmente.', 
'¿Qué llegó rápido?', '¿Qué vuela hoy?', '¿Qué llegará pronto?', 
'Actúa ya.', 'Sé veloz.', 'Fluye con el aire.', 
'Lanza un objeto.', 'Haz algo rápido.', 'Mira las nubes.', '¿Qué mensaje esperas?'),

('tarot_9_bastos', 'tarot_master', 'Nueve de Bastos', 'fuego', 'minor', 9, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La muralla que levantaste.', 'Culminación individual. Resistencia final.', 'Pronto podrás descansar.', 
'¿Cuánto aguantaste?', '¿Qué te cansa hoy?', '¿Cuándo soltarás?', 
'Resiste un poco más.', 'Mantén la guardia.', 'Confía en tu fuerza.', 
'Toca una pared.', 'Escribe "resisto".', 'Respira hondo.', '¿Qué te da fuerzas?'),

('tarot_10_bastos', 'tarot_master', 'Diez de Bastos', 'fuego', 'minor', 10, 'bastos', null, 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La carga que arrastraste.', 'Carga excesiva de proyectos.', 'Soltarás el peso pronto.', 
'¿Qué peso soltaste?', '¿Qué te aplasta hoy?', '¿Qué dejarás atrás?', 
'Sueltas la carga.', 'Pide ayuda.', 'Simplifica tu vida.', 
'Suelta un saco.', 'Tira algo viejo.', 'Descansa la espalda.', '¿Qué responsabilidad sueltas?'),

('tarot_paje_bastos', 'tarot_master', 'Paje de Bastos', 'fuego', 'court', null, 'bastos', 'paje', 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'Un niño que te inspiró.', 'Mensajero de oportunidad creativa.', 'Una idea joven vendrá.', 
'¿Qué mensaje oíste?', '¿Qué descubres hoy?', '¿Qué aprenderás?', 
'Aprende a jugar.', 'Sé curioso.', 'Emprende el viaje.', 
'Dibuja un sol.', 'Juega con fuego (vela).', 'Corre un poco.', '¿Qué aventura te llama?'),

('tarot_caballero_bastos', 'tarot_master', 'Caballero de Bastos', 'fuego', 'court', null, 'bastos', 'caballero', 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'El viaje que emprendiste.', 'Impulso hacia un objetivo. Acción.', 'Llegarás a la meta rápido.', 
'¿A dónde corriste?', '¿Cuál es tu meta hoy?', '¿A dónde irás?', 
'Controla tu ardor.', 'Lánzate sin miedo.', 'Sigue tu chispa.', 
'Cierra el puño.', 'Mira hacia adelante.', 'Viste de rojo.', '¿Qué conquista planeas?'),

('tarot_reina_bastos', 'tarot_master', 'Reina de Bastos', 'fuego', 'court', null, 'bastos', 'reina', 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'La pasión que nutriste.', 'Gestión carismática del poder.', 'Brillarás por ti misma.', 
'¿A quién inspiraste?', '¿Qué irradias hoy?', '¿Qué luz serás?', 
'Sé tú misma.', 'Nutre tu talento.', 'Domina tu fuego.', 
'Acaricia un gato.', 'Viste de oro.', 'Mírate al espejo.', '¿Qué fuego cuidas?'),

('tarot_rey_bastos', 'tarot_master', 'Rey de Bastos', 'fuego', 'court', null, 'bastos', 'rey', 'https://images.unsplash.com/photo-1590013330452-944a30e87900?w=800&q=80', 
'El líder que fuiste.', 'Arquitecto del control absoluto.', 'Gobernarás tu mundo.', 
'¿Quién te obedeció?', '¿Qué mandas hoy?', '¿Qué imperio harás?', 
'Toma el mando.', 'Ejerce tu poder.', 'Sé un líder sabio.', 
'Siéntate erguido.', 'Da una orden clara.', 'Dibuja una corona.', '¿Qué imperio diriges?'),

-- COPAS
('tarot_as_copas', 'tarot_master', 'As de Copas', 'agua', 'minor', 1, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El origen de tu amor.', 'Semilla de un nuevo sentimiento.', 'Un nuevo amor vendrá.', 
'¿Qué sentiste?', '¿Qué fluye hoy?', '¿A quién amarás?', 
'Abre tu alma.', 'Recibe el regalo.', 'Ama sin límites.', 
'Bebe agua.', 'Vierte agua.', 'Mira una fuente.', '¿A quién abres tu alma?'),

('tarot_2_copas', 'tarot_master', 'Dos de Copas', 'agua', 'minor', 2, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El pacto que hiciste.', 'Encuentro alquímico. Unión.', 'Te reconciliarás pronto.', 
'¿Con quién te uniste?', '¿A quién miras hoy?', '¿Quién vendrá?', 
'Crea el lazo.', 'Perdona de corazón.', 'Busca la armonía.', 
'Brinda con vino.', 'Mira un reflejo.', 'Da un abrazo.', '¿Qué unión estás sanando?'),

('tarot_3_copas', 'tarot_master', 'Tres de Copas', 'agua', 'minor', 3, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'La fiesta que disfrutaste.', 'Celebración compartida. Alegría.', 'Pronto habrá fiesta.', 
'¿Con quién reíste?', '¿Qué celebras hoy?', '¿Quién te alegrará?', 
'Comparte el gozo.', 'Baila en grupo.', 'Ríe sin miedo.', 
'Ríe a carcajadas.', 'Lanza pétalos.', 'Canta una oda.', '¿Qué gratitud compartes?'),

('tarot_4_copas', 'tarot_master', 'Cuatro de Copas', 'agua', 'minor', 4, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El aburrimiento pasado.', 'Estatismo emocional. Apatía.', 'Aceptarás la copa pronto.', 
'¿Qué rechazaste?', '¿Qué te cansa hoy?', '¿Qué verás luego?', 
'Acepta la oferta.', 'Mira a tu lado.', 'Sal del letargo.', 
'Cruza los brazos.', 'Mira al suelo.', 'Respira hondo.', '¿De qué te proteges?'),

('tarot_5_copas', 'tarot_master', 'Cinco de Copas', 'agua', 'minor', 5, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'La copa que lloraste.', 'Crisis afectiva. Duelo.', 'Hallarás consuelo pronto.', 
'¿Qué perdiste?', '¿Qué lloras hoy?', '¿Qué conservarás?', 
'Mira lo que queda.', 'Acepta la pérdida.', 'No te rindas.', 
'Derrama agua.', 'Viste de negro.', 'Mira atrás.', '¿Qué tristeza sueltas?'),

('tarot_6_copas', 'tarot_master', 'Seis de Copas', 'agua', 'minor', 6, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'Los juegos de infancia.', 'Nostalgia armoniosa. Inocencia.', 'Un amigo volverá.', 
'¿Qué recordaste?', '¿Qué añoras hoy?', '¿Quién regresará?', 
'Vuelve al origen.', 'Sé como un niño.', 'Perdona el pasado.', 
'Mira fotos viejas.', 'Come un dulce.', 'Juega un rato.', '¿Qué pureza conservas?'),

('tarot_7_copas', 'tarot_master', 'Siete de Copas', 'agua', 'minor', 7, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'Los sueños que tuviste.', 'Ilusiones múltiples. Deseo.', 'Elegirás bien pronto.', 
'¿Qué imaginaste?', '¿En qué sueñas hoy?', '¿Qué es real?', 
'Aterriza el sueño.', 'Elige tu verdad.', 'Descarta el humo.', 
'Dibuja nubes.', 'Mira reflejos.', 'Escribe deseos.', '¿Cuál es tu necesidad?'),

('tarot_8_copas', 'tarot_master', 'Ocho de Copas', 'agua', 'minor', 8, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El camino que dejaste.', 'Abandono voluntario. Búsqueda.', 'Hallarás la luz pronto.', 
'¿De qué huiste?', '¿Qué dejas hoy?', '¿Qué buscarás?', 
'Sigue tu camino.', 'Suelta lo viejo.', 'Camina con fe.', 
'Mira la luna.', 'Sube una montaña.', 'Camina solo.', '¿Qué buscas en soledad?'),

('tarot_9_copas', 'tarot_master', 'Nueve de Copas', 'agua', 'minor', 9, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El deseo que se cumplió.', 'Satisfacción individual. Paz.', 'Serás muy feliz pronto.', 
'¿Qué lograste?', '¿Qué gozas hoy?', '¿Qué pedirás?', 
'Goza el momento.', 'Agradece tu paz.', 'Sé generoso.', 
'Sonríe al sol.', 'Sé tu propio rey.', 'Pide un deseo.', '¿Qué regalo te haces?'),

('tarot_10_copas', 'tarot_master', 'Diez de Copas', 'agua', 'minor', 10, 'copas', null, 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'La armonía que viviste.', 'Felicidad colectiva. Plenitud.', 'Tendrás paz en casa.', 
'¿Con quién amaste?', '¿Qué paz sientes hoy?', '¿Quién te amará?', 
'Bendice tu tribu.', 'Crea un hogar.', 'Ama a todos.', 
'Dibuja un arcoíris.', 'Abraza a todos.', 'Canta en paz.', '¿Cómo se siente tu paz?'),

('tarot_paje_copas', 'tarot_master', 'Paje de Copas', 'agua', 'court', null, 'copas', 'paje', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'La ternura que mostraste.', 'Mensaje de amor. Tritón.', 'Un mensaje vendrá.', 
'¿Qué susurro oíste?', '¿Qué sientes hoy?', '¿De quién vendrá?', 
'Abre tu corazón.', 'Escucha al pez.', 'Sé vulnerable.', 
'Habla con un pez.', 'Bebe en copa roja.', 'Escribe un verso.', '¿Qué emoción te sorprende?'),

('tarot_caballero_copas', 'tarot_master', 'Caballero de Copas', 'agua', 'court', null, 'copas', 'caballero', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El romance que viviste.', 'Búsqueda del ideal. Avance.', 'El amor llegará pronto.', 
'¿A quién seguiste?', '¿A quién buscas hoy?', '¿Quién te amará?', 
'Sigue al corazón.', 'Sé un romántico.', 'Busca la copa.', 
'Caballo de agua.', 'Mira una rosa.', 'Viste de azul.', '¿Qué ideal persigues?'),

('tarot_reina_copas', 'tarot_master', 'Reina de Copas', 'agua', 'court', null, 'copas', 'reina', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'La empatía que tuviste.', 'Nutrición de las emociones.', 'Te sanarás por dentro.', 
'¿A quién cuidaste?', '¿Cómo te nutres hoy?', '¿Qué luz serás?', 
'Escucha tu alma.', 'Sé la madre.', 'Mira el cáliz.', 
'Mira el mar.', 'Toca un cristal.', 'Medita en paz.', '¿Qué secreto guardas?'),

('tarot_rey_copas', 'tarot_master', 'Rey de Copas', 'agua', 'court', null, 'copas', 'rey', 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=800&q=80', 
'El consuelo que diste.', 'Control sabio de la emoción.', 'Gobernarás tu calma.', 
'¿Quién te buscó?', '¿Qué paz das hoy?', '¿Qué mar mandarás?', 
'Domina tus olas.', 'Sé el rey sabio.', 'Mantén la calma.', 
'Siéntate en el mar.', 'Mira una tormenta.', 'Sé el centro.', '¿Qué madurez lograste?'),

-- ESPADAS
('tarot_as_espadas', 'tarot_master', 'As de Espadas', 'aire', 'minor', 1, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La decisión que tomaste.', 'Semilla de claridad mental.', 'Una verdad nacerá pronto.', 
'¿Qué verdad viste?', '¿Qué idea nace hoy?', '¿Qué cortarás?', 
'Clarifica tu mente.', 'Corta con el nudo.', 'Usa tu espada.', 
'Escribe tu verdad.', 'Afila tu mente.', 'Mira el cielo.', '¿Qué vas a declarar?'),

('tarot_2_espadas', 'tarot_master', 'Dos de Espadas', 'aire', 'minor', 2, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El dilema que tuviste.', 'Dualidad mental. Decisión ciega.', 'Elegirás con fe pronto.', 
'¿Qué no querías ver?', '¿Qué ignoras hoy?', '¿Qué verás luego?', 
'Siente el equilibrio.', 'Decide en silencio.', 'No temas la paz.', 
'Cubre tus ojos.', 'Cruza dos dedos.', 'Escucha el silencio.', '¿De qué no quieres enterarte?'),

('tarot_3_espadas', 'tarot_master', 'Tres de Espadas', 'aire', 'minor', 3, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La herida que sanaste.', 'Dolor intelectual. Ruptura.', 'El dolor pasará pronto.', 
'¿Qué te dolió?', '¿Qué te hiere hoy?', '¿Cómo sanarás?', 
'Acepta la herida.', 'Llora la verdad.', 'Cura tu mente.', 
'Dibuja un corazón.', 'Moja tu cara.', 'Respira la lluvia.', '¿Qué claridad surge?'),

('tarot_4_espadas', 'tarot_master', 'Cuatro de Espadas', 'aire', 'minor', 4, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El descanso que tomaste.', 'Descanso mental necesario. Pausa.', 'Recuperarás fuerzas pronto.', 
'¿Cuándo paraste?', '¿Qué paz buscas hoy?', '¿Qué harás luego?', 
'Retírate al centro.', 'Deja la espada.', 'Medita en calma.', 
'Inmovilidad total.', 'Silencio absoluto.', 'Mira una estatua.', '¿Dónde reside tu paz?'),

('tarot_5_espadas', 'tarot_master', 'Cinco de Espadas', 'aire', 'minor', 5, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El orgullo que pagaste.', 'Crisis mental. Victoria amarga.', 'Anderás tras la derrota.', 
'¿A quién heriste?', '¿Quién te vence hoy?', '¿Qué ganarás luego?', 
'Humilla tu ego.', 'Deja la lucha.', 'Acepta el fin.', 
'Suelta tres palos.', 'Mira al suelo.', 'Pide perdón.', '¿Qué orgullo sueltas?'),

('tarot_6_espadas', 'tarot_master', 'Seis de Espadas', 'aire', 'minor', 6, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El viaje que hiciste.', 'Transición mental. Regreso.', 'Estarás a salvo pronto.', 
'¿A dónde fuiste?', '¿Hacia qué paz vas hoy?', '¿A dónde llegarás?', 
'Cámbia de aires.', 'Suelta el lastre.', 'Rema en silencio.', 
'Cruza un puente.', 'Mira el agua.', 'Viaja en bus.', '¿Qué equipaje dejas?'),

('tarot_7_espadas', 'tarot_master', 'Siete de Espadas', 'aire', 'minor', 7, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El plan que trazaste.', 'Estrategia o astucia intelectual.', 'Llegarás a tu fin pronto.', 
'¿Qué ocultaste?', '¿Qué tramas hoy?', '¿Qué dirás?', 
'Sé cauteloso.', 'Usa tu ingenio.', 'No te delates.', 
'Camina sigiloso.', 'Guarda un secreto.', 'Lee entre líneas.', '¿De qué escapas?'),

('tarot_8_espadas', 'tarot_master', 'Ocho de Espadas', 'aire', 'minor', 8, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La venda que tuviste.', 'Prisión mental. Inmovilidad.', 'Verás la salida pronto.', 
'¿Qué te ató?', '¿Qué te ciega hoy?', '¿Cómo soltarás?', 
'Quítate la venda.', 'Camina con fe.', 'Libera tu mente.', 
'Atate la mano.', 'Cierra los ojos.', 'Mira el cielo.', '¿Quién tiene la llave?'),

('tarot_9_espadas', 'tarot_master', 'Nueve de Espadas', 'aire', 'minor', 9, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La noche que no dormiste.', 'Pesadilla intelectual. Ansiedad.', 'Amanecerá pronto.', 
'¿Qué te asustó?', '¿Qué temes hoy?', '¿Qué luz verás?', 
'Despierta ya.', 'Mira la luz.', 'Corta la sombra.', 
'Enciende una luz.', 'Grita al miedo.', 'Mira las estrellas.', '¿Qué miedo es sombra?'),

('tarot_10_espadas', 'tarot_master', 'Diez de Espadas', 'aire', 'minor', 10, 'espadas', null, 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'El fin que aceptaste.', 'Colapso mental absoluto. Fin.', 'Renacerás pronto.', 
'¿Qué terminó?', '¿Qué muere hoy?', '¿Qué nacerá?', 
'Acepta el golpe.', 'Muere al pasado.', 'Mira el sol.', 
'Túmbate al sol.', 'Deja la espada.', 'Respira el aire.', '¿Qué amanecer esperas?'),

('tarot_paje_espadas', 'tarot_master', 'Paje de Espadas', 'aire', 'court', null, 'espadas', 'paje', 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La duda que resolviste.', 'Mensajero de alerta. Astucia.', 'Una verdad joven vendrá.', 
'¿Qué advertiste?', '¿Qué vigilas hoy?', '¿Qué sabrás?', 
'Sé perspicaz.', 'Mira los detalles.', 'Afila tu palabra.', 
'Afila un lápiz.', 'Mira de reojo.', 'Escribe una denuncia.', '¿Qué verdad descubres?'),

('tarot_caballero_espadas', 'tarot_master', 'Caballero de Espadas', 'aire', 'court', null, 'espadas', 'caballero', 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La lucha que ganaste.', 'Ataque verbal. Avance veloz.', 'Cerrarás el debate pronto.', 
'¿Contra quién luchaste?', '¿Qué atacas hoy?', '¿Qué dirás?', 
'Sé implacable.', 'Usa la espada.', 'No dudes al andar.', 
'Corta el aire.', 'Corre al viento.', 'Viste de gris.', '¿Qué conflicto resuelves?'),

('tarot_reina_espadas', 'tarot_master', 'Reina de Espadas', 'aire', 'court', null, 'espadas', 'reina', 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La frialdad que tuviste.', 'Protección de la verdad objetiva.', 'Tendrás claridad final.', 
'¿A quién juzgaste?', '¿Qué cortas hoy?', '¿Qué luz serás?', 
'Corta el drama.', 'Sé una juez justa.', 'Mira al norte.', 
'Mira una espada.', 'Viste de plata.', 'Sé el aire frío.', '¿Qué claridad defiendes?'),

('tarot_rey_espadas', 'tarot_master', 'Rey de Espadas', 'aire', 'court', null, 'espadas', 'rey', 'https://images.unsplash.com/photo-1601050638911-c30207efda6d?w=800&q=80', 
'La ley que impusiste.', 'Arquitecto del control mental.', 'Gobernarás tu palabra.', 
'¿A quién sentenciaste?', '¿Qué juzgas hoy?', '¿Qué ley harás?', 
'Sentencia el fin.', 'Sé el rey sabio.', 'Mantén el criterio.', 
'Escribe una norma.', 'Mira al frente.', 'Sé el juez.', '¿Qué juicio emites hoy?'),

-- OROS
('tarot_as_oros', 'tarot_master', 'As de Oros', 'tierra', 'minor', 1, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La moneda que ganaste.', 'Semilla de prosperidad física.', 'Un regalo vendrá pronto.', 
'¿Qué riqueza viste?', '¿Qué valor nace hoy?', '¿Qué comprarás?', 
'Siembra el oro.', 'Toca la tierra.', 'Recibe el don.', 
'Toca una moneda.', 'Planta una flor.', 'Mira un árbol.', '¿Qué valor siembras?'),

('tarot_2_oros', 'tarot_master', 'Dos de Oros', 'tierra', 'minor', 2, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El cambio que manejaste.', 'Malabarismo material. Prioridades.', 'Equilibrarás tu vida pronto.', 
'¿Qué prioridades tuviste?', '¿Qué equilibras hoy?', '¿Qué elegirás?', 
'Haz el juego.', 'Sé flexible.', 'No temas caer.', 
'Haz círculos.', 'Toca dos piedras.', 'Mueve tus pies.', '¿Cómo gestionas tu energía?'),

('tarot_3_oros', 'tarot_master', 'Tres de Oros', 'tierra', 'minor', 3, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El trabajo que hiciste bien.', 'Colaboración y maestría técnica.', 'Tu obra será admirada.', 
'¿Quién te ayudó?', '¿En qué trabajas hoy?', '¿Qué construirás?', 
'Trabaja en equipo.', 'Sé un maestro.', 'Cuida el detalle.', 
'Talla algo.', 'Dibuja con regla.', 'Ordena tus herramientas.', '¿Qué obra perfeccionas?'),

('tarot_4_oros', 'tarot_master', 'Cuatro de Oros', 'tierra', 'minor', 4, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La seguridad que buscaste.', 'Apegos materiales. Seguridad.', 'Mantendrás tu tesoro.', 
'¿A qué te aferraste?', '¿Qué retienes hoy?', '¿Qué ganarás?', 
'Sultar el miedo.', 'Cuida tu tesoro.', 'Mantén el orden.', 
'Abraza un cofre.', 'Cuenta tu dinero.', 'Siente el suelo.', '¿De qué te sientes dueño?'),

('tarot_5_oros', 'tarot_master', 'Cinco de Oros', 'tierra', 'minor', 5, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La carencia que sufriste.', 'Pobreza física o falta de recursos.', 'Hallarás refugio pronto.', 
'¿Qué te faltó?', '¿Qué necesitas hoy?', '¿Quién te ayudará?', 
'Pide ayuda ya.', 'Busca el refugio.', 'No pierdas la fe.', 
'Camina en frío.', 'Mira una luz.', 'Toca una campana.', '¿Qué riqueza persiste?'),

('tarot_6_oros', 'tarot_master', 'Seis de Oros', 'tierra', 'minor', 6, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La generosidad que recibiste.', 'Intercambio. Equilibrio de deuda.', 'Te darán lo justo pronto.', 
'¿A quién diste?', '¿Qué recibes hoy?', '¿Qué pagarás?', 
'Sé generoso.', 'Acepta el pago.', 'Equilibra la balanza.', 
'Regala una moneda.', 'Pesa dos cosas.', 'Comparte tu pan.', '¿Cómo equilibras tu dar?'),

('tarot_7_oros', 'tarot_master', 'Siete de Oros', 'tierra', 'minor', 7, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La planta que cuidaste.', 'Paciencia física. Cosecha lenta.', 'Cosecharás pronto.', 
'¿Qué sembraste?', '¿Qué esperas hoy?', '¿Qué recogerás?', 
'Ten paciencia.', 'No fuerces la tierra.', 'Mira tus frutos.', 
'Toca una planta.', 'Mira el jardín.', 'Siente el tiempo.', '¿Vale la pena tu esfuerzo?'),

('tarot_8_oros', 'tarot_master', 'Ocho de Oros', 'tierra', 'minor', 8, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El aprendizaje que tuviste.', 'Dedicación al detalle. Repetición.', 'Serás un maestro pronto.', 
'¿Qué aprendiste?', '¿En qué mejoras hoy?', '¿Qué enseñarás?', 
'Sé perfeccionista.', 'Repite tu labor.', 'Ama tu oficio.', 
'Limpia un cristal.', 'Escribe con calma.', 'Repite una acción.', '¿Qué maestría forjas?'),

('tarot_9_oros', 'tarot_master', 'Nueve de Oros', 'tierra', 'minor', 9, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El confort que ganaste.', 'Independencia material. Disfrute.', 'Estarás en paz pronto.', 
'¿Con qué gozaste?', '¿Qué tienes hoy?', '¿Qué jardín harás?', 
'Disfruta tu lujo.', 'Sé independiente.', 'Sé generosa.', 
'Camina descalza.', 'Siente la seda.', 'Mira tu jardín.', '¿Qué tan rico te sientes?'),

('tarot_10_oros', 'tarot_master', 'Diez de Oros', 'tierra', 'minor', 10, 'oros', null, 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La herencia que te dejaron.', 'Legado familiar. Estabilidad total.', 'Tu casa estará llena pronto.', 
'¿Quién te dejó esto?', '¿Qué paz tienes hoy?', '¿Qué legarás?', 
'Honra tu sangre.', 'Construye tu casa.', 'Siembra tu árbol.', 
'Mira tu familia.', 'Toca una roca.', 'Bendice tu hogar.', '¿Qué es lo que perdura?'),

('tarot_paje_oros', 'tarot_master', 'Paje de Oros', 'tierra', 'court', null, 'oros', 'paje', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El tesoro que encontraste.', 'Mensajero de noticia económica.', 'Un regalo físico vendrá.', 
'¿Qué moneda viste?', '¿Qué estudias hoy?', '¿Qué ganarás?', 
'Eudia la tierra.', 'Toca lo real.', 'Siembra tu oro.', 
'Toca una semilla.', 'Mira una piedra.', 'Viste de verde.', '¿Qué nuevo objeto te atrae?'),

('tarot_caballero_oros', 'tarot_master', 'Caballero de Oros', 'tierra', 'court', null, 'oros', 'caballero', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El esfuerzo sólido.', 'Avance lento hacia un fin financiero.', 'Llegarás al éxito pronto.', 
'¿Cuánto trabajaste?', '¿Qué plan sigues hoy?', '¿Qué ganarás?', 
'Sé metódico.', 'No tengas prisa.', 'Confía en el paso.', 
'Camina despacio.', 'Cuenta tus ahorros.', 'Siente el peso.', '¿Cuál es tu plan hoy?'),

('tarot_reina_oros', 'tarot_master', 'Reina de Oros', 'tierra', 'court', null, 'oros', 'reina', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'La abundancia que diste.', 'Gestión de la fertilidad material.', 'Tendrás todo lo que buscas.', 
'¿A quién nutriste?', '¿Qué cocinas hoy?', '¿Qué luz serás?', 
'Nutre tu cuerpo.', 'Cura la materia.', 'Sé la tierra.', 
'Cocina algo rico.', 'Toca una planta.', 'Mírate al espejo.', '¿Qué abundancia cuidas?'),

('tarot_rey_oros', 'tarot_master', 'Rey de Oros', 'tierra', 'court', null, 'oros', 'rey', 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=800&q=80', 
'El bienestar que lograste.', 'Arquitecto del control material.', 'Gobernarás tu riqueza.', 
'¿Quién te financió?', '¿Qué mandas hoy?', '¿Qué imperio harás?', 
'Sé el dueño.', 'Ejerce tu control.', 'Haz las leyes.', 
'Cuenta tu dinero.', 'Siéntate firme.', 'Mira tu reino.', '¿Qué imperio has forjado?');
